services:
  - type: web
    name: microgrid
    env: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PNPM_VERSION
        value: 8
